language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
env:
  - IPYTHON_VERSION=>0.10,<1.0 
  - IPYTHON_VERSION=>1.0 
install:
  - pip install -q 'ipython$IPYTHON_VERSION'
# command to run tests
script: python setup.py test
